local M = {
  ---@type table<string, boolean>
  ignored_filetypes = {
    "",
    "TelescopePrompt",
    "TelescopeResults",
    "alpha",
    "dashboard",
    "help",
    "lazy",
    "lspinfo",
    "mason",
    "neo-tree",
    "nvcheatsheet",
    "nvdash",
    "starter",
    "terminal",
  },
  root_markers = {
    ".git",
    ".github",
    "mvnw",
    "gradlew",
    "pom.xml",
    "build.gradle",
    "package.json",
    "lua/",
    "Makefile",
    "Makefile.am",
  },
  close_on_q = {
    "PlenaryTestPopup",
    "help",
    "lspinfo",
    "notify",
    "qf",
    "query",
    "spectre_panel",
    "startuptime",
    "tsplayground",
    "neotest-output",
    "checkhealth",
    "neotest-summary",
    "neotest-output-panel",
    "git", -- used for fugitive
  },
}
return M
